# Generated by Django 4.2 on 2024-08-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_datacenter_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
    ]
